dev_addr: '127.0.0.1:8001'
site_name: "Appsembler Roles"
site_url: "https://github.com/appsembler/roles"
site_description: "Curated Ansible roles with an emphasis on sane defaults, extensibility, and reusability"
pages:
  - 'Installation': index.md
  - 'Best Practices': best-practices.md
  - 'Roles': roles.md
theme: readthedocs
markdown_extensions:
  - toc:
      anchorlink: True
  - admonition:
